// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBYcaFYQyG4P6yQWgUKmw2oBOy8Q1rlBA',
    appId: '1:26901793207:web:c0cbbedddf4e2aacbb0032',
    messagingSenderId: '26901793207',
    projectId: 'instacard-36edb',
    authDomain: 'instacard-36edb.firebaseapp.com',
    databaseURL: 'https://instacard-36edb-default-rtdb.firebaseio.com',
    storageBucket: 'instacard-36edb.appspot.com',
    measurementId: 'G-HRG9JHVM15',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxHNdcRfkl6fDOr2Sdyse6ldueJ79Vm7c',
    appId: '1:26901793207:android:d2ac7091adc5f81dbb0032',
    messagingSenderId: '26901793207',
    projectId: 'instacard-36edb',
    databaseURL: 'https://instacard-36edb-default-rtdb.firebaseio.com',
    storageBucket: 'instacard-36edb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh6XIw8rXqD7CSBGh-mTD24tC_OTXi0Lc',
    appId: '1:26901793207:ios:cefd275f048937d6bb0032',
    messagingSenderId: '26901793207',
    projectId: 'instacard-36edb',
    databaseURL: 'https://instacard-36edb-default-rtdb.firebaseio.com',
    storageBucket: 'instacard-36edb.appspot.com',
    iosBundleId: 'com.instacard.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh6XIw8rXqD7CSBGh-mTD24tC_OTXi0Lc',
    appId: '1:26901793207:ios:cefd275f048937d6bb0032',
    messagingSenderId: '26901793207',
    projectId: 'instacard-36edb',
    databaseURL: 'https://instacard-36edb-default-rtdb.firebaseio.com',
    storageBucket: 'instacard-36edb.appspot.com',
    iosBundleId: 'com.instacard.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBYcaFYQyG4P6yQWgUKmw2oBOy8Q1rlBA',
    appId: '1:26901793207:web:16e2c5753b65e566bb0032',
    messagingSenderId: '26901793207',
    projectId: 'instacard-36edb',
    authDomain: 'instacard-36edb.firebaseapp.com',
    databaseURL: 'https://instacard-36edb-default-rtdb.firebaseio.com',
    storageBucket: 'instacard-36edb.appspot.com',
    measurementId: 'G-70RG9QG8TD',
  );
}
